/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.LocalTime;


/**
 *
 * @author minely
 */
public class RegistroVenta extends javax.swing.JFrame {
    private Usuario usuarioActual;
    private DefaultTableModel modeloTabla;
    private ArrayList<VentaLibros> cliente = new ArrayList<>();
   
    /**
     * Creates new form RegistroVenta
     */
    public RegistroVenta(Usuario usuario) {
        initComponents();
        cargarDatos();
        this.usuarioActual = usuario;
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
         modeloTabla = new DefaultTableModel(new String[]{"N.","Libro","Cantidad", "Precio unitario", "Subtotal","IVA","Total a pagar","Acción"}, 0);
        jTable1.setModel(modeloTabla);
        jComboBox1.removeAllItems();
      for (Libros libro :  ControladorDato.getListas().getLibros()) {
         jComboBox1.addItem(libro.getTitulo());  // solo el título
     }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel1.setText("Datos cliente:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel2.setText("Elija el libro");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel3.setText("Cantidad");

        jLabel6.setText("NIT");

        jLabel7.setText("Nombre");

        jLabel9.setText("Dirección");

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel4.setText("Subtotal");

        jLabel5.setText("Descuento");

        jLabel8.setText("IVA");

        jLabel10.setText("Total a pagar");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton1.setText("Registrar venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(59, 59, 59)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButton1)
                                .addGap(292, 292, 292)
                                .addComponent(jButton2)
                                .addGap(84, 84, 84))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextField2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField5)
                            .addComponent(jTextField6)
                            .addComponent(jTextField8)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3))
                            .addComponent(jLabel2))
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addGap(99, 99, 99)))
                .addGap(30, 40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
    class ButtonRenderer extends javax.swing.JButton implements javax.swing.table.TableCellRenderer {
    public ButtonRenderer() {
        setText("Eliminar");
    }

    @Override
    public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {
        return this;
    }
}
class ButtonEditor extends javax.swing.DefaultCellEditor {
    private javax.swing.JButton button;
    private DefaultTableModel model;
    private javax.swing.JTable table;

    public ButtonEditor(javax.swing.JCheckBox checkBox, DefaultTableModel model, javax.swing.JTable table) {
        super(checkBox);
        this.model = model;
        this.table = table;
        button = new javax.swing.JButton("Eliminar");
        button.addActionListener(e -> {
            int row = table.getSelectedRow();
            if (row >= 0) {
                model.removeRow(row);
            }
        });
    }

    @Override
    public java.awt.Component getTableCellEditorComponent(javax.swing.JTable table, Object value,
            boolean isSelected, int row, int column) {
        return button;
    }
}    
    
    private void agregarBotonEliminar() {
    jTable1.getColumn("Acción").setCellRenderer(new ButtonRenderer());
    jTable1.getColumn("Acción").setCellEditor(new ButtonEditor(new javax.swing.JCheckBox(), modeloTabla, jTable1));
}
    
    
    private void agregarLibroATabla(Libros libro, int cantidad) {
   
       
        double precio = libro.getPrecio();
        double subtotal = precio * cantidad;
        double iva = Math.round(subtotal * 0.12 * 100.0) / 100.0;
        double total = subtotal + iva;

        Object[] fila = new Object[]{
            modeloTabla.getRowCount() + 1,
            libro.getTitulo(),
            cantidad,
            precio,
            subtotal,
            iva,
            total,
            "Eliminar"
        };

        modeloTabla.addRow(fila);
        agregarBotonEliminar();
}
    
      private void cargarDatos(){
        cliente.add(new VentaLibros("12034","Minely", "Guatemala"));
    }
    
    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        try {
       
        int cantidad = Integer.parseInt(jTextField1.getText().trim());
        
        
        if (cantidad <= 0) {
            jTextField6.setText("Cantidad no válida");
            return;
        }
        
       
        int index = jComboBox1.getSelectedIndex();
        if (index >= 0) {
            Libros libro = ControladorDato.getListas().getLibros().get(index);
            
            
            double total = libro.getPrecio() * cantidad;
            
          
            jTextField6.setText(String.valueOf(total));
        }
    }  catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido en cantidad."); 
    }
        jTextField6.setText("0");
    
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         int index = jComboBox1.getSelectedIndex();
    if (index < 0) {
        JOptionPane.showMessageDialog(this, "Debes seleccionar un libro.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    Libros libro = ControladorDato.getListas().getLibros().get(index);
    int cantidadSolicitada;

    try {
        cantidadSolicitada = Integer.parseInt(jTextField1.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Cantidad inválida.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (libro.getCantidad() <= 0) {
        JOptionPane.showMessageDialog(this, "Este libro no tiene existencias.", "Sin stock", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (cantidadSolicitada > libro.getCantidad()) {
        JOptionPane.showMessageDialog(this, "No hay suficientes unidades disponibles.", "Cantidad excedida", JOptionPane.WARNING_MESSAGE);
        return;
    }
     agregarLibroATabla(libro, cantidadSolicitada);
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double subtotal = 0, iva = 0, total = 0;
    
        for (int  i = 0; i < modeloTabla.getRowCount(); i++){
            subtotal += (double) modeloTabla.getValueAt(i, 4);
             iva += (double) modeloTabla.getValueAt(i, 5);
                     total += (double) modeloTabla.getValueAt(i, 6);
        }
     
    String codigoCupon = jTextField6.getText().trim();  // Campo de entrada del cupón
    double descuento = 0;
    boolean cuponValido = false;
    Cupones cupon =  null;
    for (Cupones c : ControladorDato.getListas().getCupones()) {
        if (c.getcodigo().equalsIgnoreCase(codigoCupon)) {
            cupon  = c;
            
            
          // Validar vencimiento
        if (c.getfecha().isBefore(LocalDate.now())) {
            JOptionPane.showMessageDialog(this, "El cupón ha vencido.", "Cupón inválido", JOptionPane.ERROR_MESSAGE);
            break;
        }

        // Validar usos disponibles
        if (c.getUsosDisponibles() <= 0) {
            JOptionPane.showMessageDialog(this, "El cupón ya no tiene usos disponibles.", "Cupón inválido", JOptionPane.ERROR_MESSAGE);
            break;
        }   
        descuento = c.getvalor(total);  // Aplica descuento
            cuponValido = true;
             c.setUsosDisponibles(c.getUsosDisponibles() - 1);
            break;
            
        }
    }
    
    
if (cuponValido) {
    if ("porcentaje".equalsIgnoreCase(cupon.getTipo())) {
        jTextField6.setText(String.format("%.2f%%", cupon.getValorOriginal()));  // Aquí sólo el valor sin calcular
    } else {
        jTextField6.setText(String.format("%.2f", cupon.getvalor()));
    }
} else {
    JOptionPane.showMessageDialog(this, "Cupón inválido o no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
    jTextField6.setText("0.00");
    descuento = 0;
}

    
    double totalConDescuento = total - descuento;

    // Mostrar valores en los campos
    jTextField5.setText(String.format("%.2f", subtotal));
    jTextField7.setText(String.format("%.2f", iva));
    jTextField8.setText(String.format("%.2f", totalConDescuento));
   

    
    String nit = jTextField2.getText();
    String nombre = jTextField3.getText();
    String direccion = jTextField4.getText();
    String vendedor = usuarioActual.getNombre();
    LocalDate fecha = LocalDate.now();
    LocalTime hora = LocalTime.now();
    
    for (int i = 0; i < modeloTabla.getRowCount(); i++) {
    String tituloTabla = (String) modeloTabla.getValueAt(i, 1);
    int cantidadVendida = (int) modeloTabla.getValueAt(i, 2);

    Libros libroVendido = null;
    for (Libros libro :  ControladorDato.getListas().getLibros()) {
        if (libro.getTitulo().equals(tituloTabla)) {
            libroVendido = libro;
            break;
        }
    }
 
    VentaLibros venta = new VentaLibros(nit,nombre,descuento, direccion, totalConDescuento, usuarioActual, fecha, hora, cuponValido ? cupon.getTipo() : "ninguno",
    cuponValido ? cupon.getValorOriginal(): 0, libroVendido, cantidadVendida);
    Rventa.agregarVenta(venta);

     libroVendido.setCantidad(libroVendido.getCantidad() - cantidadVendida);
   
    }
    jComboBox1.removeAllItems();
    for (Libros libro :  ControladorDato.getListas().getLibros()) {
        jComboBox1.addItem(libro.getTitulo());  // solo muestra el título
    }
    modeloTabla.setRowCount(0);

    JOptionPane.showMessageDialog(this, "Venta registrada exitosamente.");
 
    jTextField6.setText("");
    jTextField5.setText("");
    jTextField7.setText("");
    jTextField8.setText("");


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      
    String nitBuscado = jTextField2.getText().trim();
    boolean encontrado = false;

    for (VentaLibros c : cliente) {
        if (c.getNitcliente().equals(nitBuscado)) {
            jTextField3.setText(c.getNombreCliente());
            jTextField4.setText(c.getDireccion());
            encontrado = true;
            break;
        }
    }

    if (!encontrado) {
        JOptionPane.showMessageDialog(this, "Cliente no encontrado");
        jTextField3.setText("");
        jTextField4.setText("");
    }
   
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
